name: 'Publish Marketplace Changes'
description: 'Creates a PR with marketplace changes, enables auto-merge, and creates OpenCode releases'
author: 'Bitcomplete'

inputs:
  github-token:
    description: 'GitHub token for creating PRs'
    required: true
  auto-merge:
    description: 'Enable auto-merge for generated PR'
    required: false
    default: 'true'
  create-opencode-release:
    description: 'Create OpenCode-compatible plugin releases'
    required: false
    default: 'false'
  release-version:
    description: 'Version for releases (default: YYYY.MM.DD)'
    required: false
    default: ''

outputs:
  pr-number:
    description: 'Pull request number if created'
    value: ${{ steps.create-pr.outputs.pull-request-number }}
  pr-url:
    description: 'Pull request URL if created'
    value: ${{ steps.create-pr.outputs.pull-request-url }}
  releases-created:
    description: 'Number of OpenCode releases created'
    value: ${{ steps.opencode-release.outputs.count }}

runs:
  using: 'composite'
  steps:
    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
      with:
        token: ${{ inputs.github-token }}
        base: main
        commit-message: 'chore: update marketplace.json'
        title: 'chore: update marketplace.json'
        body: |
          Auto-generated marketplace.json and plugin.json updates from plugin component changes.

          This PR is automatically created when plugin components are added, modified, or removed on the main branch.

          The files are regenerated based on:
          - Plugins discovered in two-level hierarchy: `category/plugin-name/`
          - Plugin components: agents/, commands/, skills/
          - Hooks in `hooks/hooks.json`
          - MCP servers in `.mcp.json`
          - Settings in `.claude-plugin/generator.config.toml` or `.claude-plugin/generator.config.json`

          **Generated files:**
          - `.claude-plugin/marketplace.json` - marketplace manifest with unique source paths per plugin
          - `category/plugin-name/.claude-plugin/plugin.json` - individual plugin metadata

          **This PR will auto-merge after CI checks pass.**
        branch: auto-update-marketplace
        delete-branch: true
        labels: |
          automated
          marketplace

    - name: Enable auto-merge
      if: ${{ inputs.auto-merge == 'true' && steps.create-pr.outputs.pull-request-number != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ steps.create-pr.outputs.pull-request-number }}
      run: |
        echo "Enabling auto-merge for PR #$PR_NUMBER"
        if ! gh pr merge "$PR_NUMBER" --auto --squash; then
          echo "::warning::Auto-merge could not be enabled (allow_auto_merge may not be enabled on this repo)"
        fi

    - name: Create OpenCode Releases
      id: opencode-release
      if: ${{ inputs.create-opencode-release == 'true' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        RELEASE_VERSION: ${{ inputs.release-version }}
      run: |
        set -e

        # Use bundled script from this action
        SCRIPT_PATH="${GITHUB_ACTION_PATH}/../../scripts/dist/opencode-release.cjs"

        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "ERROR: Bundled script not found at $SCRIPT_PATH" >&2
          exit 1
        fi

        echo "Creating OpenCode releases..."
        node "$SCRIPT_PATH" opencode-release

        echo "✓ Release creation complete"

branding:
  icon: 'upload-cloud'
  color: 'purple'
