name: 'Generate Marketplace Files'
description: 'Generates marketplace.json and plugin.json files from discovered components'
author: 'Bitcomplete'

inputs:
  config-path:
    description: 'Path to generator.config.toml'
    required: false
    default: '.claude-plugin/generator.config.toml'

runs:
  using: 'composite'
  steps:
    - name: Generate marketplace files
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
      run: |
        set -e

        # Use bundled script from this action
        SCRIPT_PATH="${GITHUB_ACTION_PATH}/../../scripts/dist/discover-components.cjs"

        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "ERROR: Bundled script not found at $SCRIPT_PATH" >&2
          exit 1
        fi

        echo "Generating marketplace files..."
        node "$SCRIPT_PATH" generate

        echo "✓ Generation complete"

branding:
  icon: 'file-text'
  color: 'purple'
