name: 'Generate Marketplace Files'
description: 'Generates marketplace.json and plugin.json files from discovered components'
author: 'Bitcomplete'

inputs:
  config-path:
    description: 'Path to generator.config.toml'
    required: false
    default: '.claude-plugin/generator.config.toml'

runs:
  using: 'composite'
  steps:
    - name: Generate marketplace files
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
      run: |
        set -e

        # Use bundled script from this action
        SCRIPT_PATH="${GITHUB_ACTION_PATH}/../../scripts/dist/discover-components.cjs"

        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "ERROR: Bundled script not found at $SCRIPT_PATH" >&2
          exit 1
        fi

        MARKETPLACE_FILE=".claude-plugin/marketplace.json"

        # Save existing marketplace.json for comparison
        BEFORE_FILE=$(mktemp)
        if [ -f "$MARKETPLACE_FILE" ]; then
          cp "$MARKETPLACE_FILE" "$BEFORE_FILE"
          HAD_FILE=true
        else
          : > "$BEFORE_FILE"
          HAD_FILE=false
        fi

        echo "Generating marketplace files..."
        node "$SCRIPT_PATH" generate

        # Write job summary
        if [ -n "$GITHUB_STEP_SUMMARY" ]; then
          {
            echo "### Generate"
            echo ""

            if [ "$HAD_FILE" = "false" ] && [ -f "$MARKETPLACE_FILE" ]; then
              echo "📄 **New file** — \`$MARKETPLACE_FILE\`"
              echo ""
              echo '```diff'
              sed 's/^/+ /' "$MARKETPLACE_FILE"
              echo '```'
            elif diff -q "$BEFORE_FILE" "$MARKETPLACE_FILE" > /dev/null 2>&1; then
              echo "No changes to \`$MARKETPLACE_FILE\`"
            else
              echo "📦 **Updated** \`$MARKETPLACE_FILE\`"
              echo ""
              echo '```diff'
              # diff exits 1 when files differ; neutralize before the pipe
              { diff -u "$BEFORE_FILE" "$MARKETPLACE_FILE" || true; } | tail -n +3
              echo '```'
            fi
          } >> "$GITHUB_STEP_SUMMARY"
          rm -f "$BEFORE_FILE"
        fi

        echo "✓ Generation complete"

branding:
  icon: 'file-text'
  color: 'purple'
