name: 'Generate Marketplace Files'
description: 'Generates marketplace.json and plugin.json files from discovered components'
author: 'Bitcomplete'

inputs:
  config-path:
    description: 'Path to generator.config.toml'
    required: false
    default: '.claude-plugin/generator.config.toml'

runs:
  using: 'composite'
  steps:
    - name: Generate marketplace files
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
      run: |
        set -e

        # Use bundled script from this action
        SCRIPT_PATH="${GITHUB_ACTION_PATH}/../../scripts/dist/discover-components.cjs"

        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "ERROR: Bundled script not found at $SCRIPT_PATH" >&2
          exit 1
        fi

        MARKETPLACE_FILE=".claude-plugin/marketplace.json"

        # Save existing marketplace.json for comparison
        if [ -f "$MARKETPLACE_FILE" ]; then
          BEFORE=$(cat "$MARKETPLACE_FILE")
          HAD_FILE=true
        else
          BEFORE=""
          HAD_FILE=false
        fi

        echo "Generating marketplace files..."
        node "$SCRIPT_PATH" generate

        # Write job summary
        if [ -n "$GITHUB_STEP_SUMMARY" ]; then
          if [ -f "$MARKETPLACE_FILE" ]; then
            AFTER=$(cat "$MARKETPLACE_FILE")
          else
            AFTER=""
          fi

          {
            echo "### Generate"
            echo ""

            if [ "$HAD_FILE" = "false" ] && [ -n "$AFTER" ]; then
              echo "📄 **New file** — \`$MARKETPLACE_FILE\`"
              echo ""
              echo "<details><summary>marketplace.json</summary>"
              echo ""
              echo '```json'
              echo "$AFTER"
              echo '```'
              echo ""
              echo "</details>"
            elif [ "$BEFORE" = "$AFTER" ]; then
              echo "No changes to \`$MARKETPLACE_FILE\`"
            else
              PLUGIN_LIST=$(node -e "
                const m = JSON.parse(process.argv[1]);
                m.plugins.forEach(p => console.log('- **' + p.name + '** (' + p.category + '): ' + p.description));
              " "$AFTER")
              echo "📦 **Updated** \`$MARKETPLACE_FILE\`"
              echo ""
              echo "$PLUGIN_LIST"
              echo ""
              echo "<details><summary>Full marketplace.json</summary>"
              echo ""
              echo '```json'
              echo "$AFTER"
              echo '```'
              echo ""
              echo "</details>"
            fi
          } >> "$GITHUB_STEP_SUMMARY"
        fi

        echo "✓ Generation complete"

branding:
  icon: 'file-text'
  color: 'purple'
